# Generated by Django 3.2.25 on 2024-06-03 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestresult',
            name='sold_at_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 3, 0, 55, 34, 835498)),
        ),
    ]
