# Generated by Django 3.2.25 on 2024-06-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0003_auto_20240601_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='high',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='low',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='open',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='volume',
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
