# Generated by Django 3.2.25 on 2024-06-03 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0004_auto_20240602_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='sold_at_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 2, 23, 29, 38, 57792)),
        ),
    ]
